# -*- coding: utf-8 -*-
"""projeto_redes_complexas_Larissa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14AkoTYo0HTwghLFjIaDJI7zI-8nwIVbg
"""

# Instala as bibliotecas necessárias para leitura de PDB,
# análise de redes, manipulação de dados e visualização 3D.

#!pip install biopython py3Dmol

# Importa as bibliotecas utilizadas no projeto e cria as pastas
# onde serão salvos os resultados, tabelas e figuras.

import os
import time
import tarfile
from pathlib import Path

import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import py3Dmol

from Bio.PDB import PDBParser
from scipy.spatial import cKDTree
from networkx.algorithms.community import louvain_communities
from networkx.algorithms.community.quality import modularity

# Permite usar display() tanto no Jupyter/Colab quanto ao executar como script local.
try:
    from IPython.display import display
except ImportError:
    def display(obj):
        print(obj)


# Permite exibir visualizações 3D apenas em ambiente interativo
# (Jupyter/Google Colab). Ao executar este arquivo como script local
# pelo Terminal, as visualizações py3Dmol são ignoradas para evitar erro.
def show_3d_view(view, description="visualização 3D"):
    try:
        from IPython import get_ipython
        shell = get_ipython()

        if shell is None or shell.__class__.__name__ == "TerminalInteractiveShell":
            print(f"{description} ignorada: execute esta etapa no notebook/Colab para visualizar em 3D.")
            return

        view.zoomTo()
        view.show()

    except Exception as error:
        print(f"{description} ignorada: não foi possível renderizar a visualização 3D neste ambiente.")
        print(f"Motivo: {error}")

# ==========================================================
# Configuração de caminhos do projeto
#
# Este arquivo .py está dentro da pasta notebook/.
# Por isso, a raiz do projeto é a pasta imediatamente acima.
#
# Estrutura esperada:
# projeto_redes_complexas/
# ├── data/
# ├── notebook/
# ├── report/
# └── results/
# ==========================================================

BASE_DIR = Path(__file__).resolve().parent
PROJECT_DIR = BASE_DIR.parent

DATA_DIR = PROJECT_DIR / "data"
RESULTS_DIR = PROJECT_DIR / "results"
FIGURES_DIR = RESULTS_DIR / "figures"
TABLES_DIR = RESULTS_DIR / "tables"

RESULTS_DIR.mkdir(exist_ok=True)
FIGURES_DIR.mkdir(parents=True, exist_ok=True)
TABLES_DIR.mkdir(parents=True, exist_ok=True)

pdb_1ubq = DATA_DIR / "1UBQ.pdb"
tar_6b1t = DATA_DIR / "6b1t-pdb-bundle.tar"
extract_dir = DATA_DIR / "6b1t_files"

# Lê um arquivo PDB e extrai apenas os resíduos que possuem átomo Cα.
# Cada resíduo será representado como um nó da rede.

def extract_ca_residues(pdb_file, structure_id="protein"):
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure(structure_id, str(pdb_file))

    data = []

    for model in structure:
        for chain in model:
            for residue in chain:
                if "CA" in residue:
                    ca = residue["CA"]
                    x, y, z = ca.coord

                    data.append({
                        "node": len(data),
                        "chain": chain.id,
                        "resname": residue.get_resname(),
                        "resid": residue.id[1],
                        "x": float(x),
                        "y": float(y),
                        "z": float(z)
                    })
        break

    return pd.DataFrame(data)

# Constrói uma rede de contatos não direcionada e não ponderada.
# Dois resíduos são conectados se a distância entre seus Cα for <= cutoff.

def build_contact_graph(df_residues, cutoff=8.0):
    G = nx.Graph()

    for _, row in df_residues.iterrows():
        G.add_node(
            int(row["node"]),
            chain=row["chain"],
            resname=row["resname"],
            resid=int(row["resid"]),
            x=row["x"],
            y=row["y"],
            z=row["z"]
        )

    coords = df_residues[["x", "y", "z"]].values
    tree = cKDTree(coords)
    pairs = tree.query_pairs(r=cutoff)

    for i, j in pairs:
        G.add_edge(i, j)

    return G

# Calcula estatísticas gerais da rede.

def calculate_graph_statistics(G):
    degrees = np.array([d for _, d in G.degree()])

    stats = {
        "nodes": G.number_of_nodes(),
        "edges": G.number_of_edges(),
        "density": nx.density(G),
        "average_degree": degrees.mean(),
        "minimum_degree": degrees.min(),
        "maximum_degree": degrees.max(),
        "median_degree": np.median(degrees),
        "connected_components": nx.number_connected_components(G),
        "largest_component": len(max(nx.connected_components(G), key=len)),
        "average_clustering": nx.average_clustering(G)
    }

    return pd.DataFrame([stats])

# Aplica o algoritmo Louvain e salva a comunidade de cada nó como atributo.

def detect_louvain(G, seed=42):
    communities = louvain_communities(G, seed=seed)

    partition = {}

    for community_id, community in enumerate(communities):
        for node in community:
            partition[node] = community_id

    nx.set_node_attributes(G, partition, "community")

    return communities, partition

# Gera histograma e gráfico log-log da distribuição de graus.

def plot_degree_distribution(G, title, output_path):
    degrees = np.array([d for _, d in G.degree()])
    unique, counts = np.unique(degrees, return_counts=True)
    pk = counts / counts.sum()

    fig, ax = plt.subplots(1, 2, figsize=(14, 5))

    ax[0].hist(degrees, bins=30, edgecolor="black")
    ax[0].set_title("Histograma dos graus")
    ax[0].set_xlabel("Grau")
    ax[0].set_ylabel("Frequência")

    ax[1].scatter(unique, pk, s=40)
    ax[1].set_xscale("log")
    ax[1].set_yscale("log")
    ax[1].set_xlabel("Grau k")
    ax[1].set_ylabel("P(k)")
    ax[1].set_title("Distribuição em escala log-log")
    ax[1].grid(alpha=0.3)

    plt.suptitle(title)
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.show()

# Plota a rede em 2D colorida pelas comunidades.

def plot_community_graph(G, partition, title, output_path):
    colors = [partition[node] for node in G.nodes()]
    pos = nx.spring_layout(G, seed=42)

    plt.figure(figsize=(8, 8))
    nx.draw_networkx_nodes(
        G,
        pos,
        node_color=colors,
        cmap=plt.cm.tab20,
        node_size=80
    )
    nx.draw_networkx_edges(G, pos, alpha=0.3)
    plt.axis("off")
    plt.title(title)

    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.show()

# Executa o pipeline completo para a proteína pequena 1UBQ.
# Esta etapa valida o funcionamento do código antes da aplicação na 6B1T.

df_1ubq = extract_ca_residues(pdb_1ubq, "1UBQ")
G_1ubq = build_contact_graph(df_1ubq, cutoff=8.0)
communities_1ubq, partition_1ubq = detect_louvain(G_1ubq)

stats_1ubq = calculate_graph_statistics(G_1ubq)
stats_1ubq.to_csv(TABLES_DIR / "1UBQ_graph_statistics.csv", index=False)

print("1UBQ")
print("Nós:", G_1ubq.number_of_nodes())
print("Arestas:", G_1ubq.number_of_edges())
print("Comunidades:", len(communities_1ubq))
display(stats_1ubq)

# Calcula centralidades completas na proteína de teste.
# Como a 1UBQ é pequena, é possível calcular métricas mais custosas.

degree_c_1ubq = nx.degree_centrality(G_1ubq)
betweenness_1ubq = nx.betweenness_centrality(G_1ubq)
closeness_1ubq = nx.closeness_centrality(G_1ubq)
eigenvector_1ubq = nx.eigenvector_centrality(G_1ubq, max_iter=1000)

df_centrality_1ubq = pd.DataFrame([
    {
        "node": node,
        "chain": G_1ubq.nodes[node]["chain"],
        "resname": G_1ubq.nodes[node]["resname"],
        "resid": G_1ubq.nodes[node]["resid"],
        "degree": G_1ubq.degree(node),
        "degree_centrality": degree_c_1ubq[node],
        "betweenness_centrality": betweenness_1ubq[node],
        "closeness_centrality": closeness_1ubq[node],
        "eigenvector_centrality": eigenvector_1ubq[node],
        "community": partition_1ubq[node]
    }
    for node in G_1ubq.nodes()
])

df_centrality_1ubq.to_csv(
    TABLES_DIR / "1UBQ_centralities.csv",
    index=False
)

df_centrality_1ubq.sort_values("degree", ascending=False).head(10)

# Gera a figura da rede da proteína de teste colorida por comunidades.
# Esta figura será usada na seção de validação do pipeline.

plot_community_graph(
    G_1ubq,
    partition_1ubq,
    "Rede de contatos da proteína 1UBQ",
    FIGURES_DIR / "1UBQ_community_graph.png"
)

# Descompacta o pacote da estrutura 6B1T baixado do PDB.

tar_path = tar_6b1t

if not extract_dir.exists():
    with tarfile.open(tar_path, "r") as tar:
        tar.extractall(extract_dir)

for root, dirs, files in os.walk(extract_dir):
    for file in files:
        print(os.path.join(root, file))

# A estrutura 6B1T vem dividida em dois arquivos PDB.
# Os dois arquivos são lidos e integrados em uma única tabela de resíduos.

pdb_6b1t_1 = extract_dir / "6b1t-pdb-bundle1.pdb"
pdb_6b1t_2 = extract_dir / "6b1t-pdb-bundle2.pdb"

df_6b1t_1 = extract_ca_residues(pdb_6b1t_1, "6B1T_1")
df_6b1t_2 = extract_ca_residues(pdb_6b1t_2, "6B1T_2")

df_6b1t = pd.concat([df_6b1t_1, df_6b1t_2], ignore_index=True)
df_6b1t["node"] = range(len(df_6b1t))

print("Bundle 1:", df_6b1t_1.shape)
print("Bundle 2:", df_6b1t_2.shape)
print("Total:", df_6b1t.shape)

df_6b1t.to_csv(TABLES_DIR / "6B1T_residues.csv", index=False)

df_6b1t.head()

# Testa diferentes valores de cutoff para avaliar o impacto
# na densidade da rede, modularidade e número de comunidades.

def test_cutoffs(df_residues, cutoffs, seed=42):
    results = []

    for cutoff in cutoffs:
        print(f"Testando cutoff = {cutoff} Å")
        start = time.time()

        G_temp = build_contact_graph(df_residues, cutoff=cutoff)
        communities_temp, partition_temp = detect_louvain(G_temp, seed=seed)
        mod = modularity(G_temp, communities_temp)

        degrees = np.array([d for _, d in G_temp.degree()])

        results.append({
            "cutoff": cutoff,
            "nodes": G_temp.number_of_nodes(),
            "edges": G_temp.number_of_edges(),
            "avg_degree": degrees.mean(),
            "max_degree": degrees.max(),
            "num_communities": len(communities_temp),
            "modularity": mod,
            "time_seconds": time.time() - start
        })

    return pd.DataFrame(results)

cutoffs = [6.0, 7.0, 8.0, 9.0, 10.0]

df_cutoffs = test_cutoffs(df_6b1t, cutoffs)
df_cutoffs.to_csv(TABLES_DIR / "6B1T_cutoff_tests.csv", index=False)

df_cutoffs

# Gera gráficos para visualizar como o cutoff altera
# o número de comunidades e a modularidade.

plt.figure(figsize=(7, 4))
plt.plot(df_cutoffs["cutoff"], df_cutoffs["num_communities"], marker="o")
plt.xlabel("Cutoff de distância (Å)")
plt.ylabel("Número de comunidades")
plt.title("Número de comunidades por cutoff - 6B1T")
plt.grid(True)
plt.savefig(FIGURES_DIR / "6B1T_cutoff_communities.png", dpi=300, bbox_inches="tight")
plt.show()

plt.figure(figsize=(7, 4))
plt.plot(df_cutoffs["cutoff"], df_cutoffs["modularity"], marker="o")
plt.xlabel("Cutoff de distância (Å)")
plt.ylabel("Modularidade")
plt.title("Modularidade por cutoff - 6B1T")
plt.grid(True)
plt.savefig(FIGURES_DIR / "6B1T_cutoff_modularity.png", dpi=300, bbox_inches="tight")
plt.show()

# Constrói a rede final da proteína 6B1T usando cutoff = 8 Å,
# escolhido como equilíbrio entre densidade, modularidade e comunidades.

G_6b1t = build_contact_graph(df_6b1t, cutoff=8.0)
communities_6b1t, partition_6b1t = detect_louvain(G_6b1t)

stats_6b1t = calculate_graph_statistics(G_6b1t)
stats_6b1t.to_csv(TABLES_DIR / "6B1T_graph_statistics.csv", index=False)

print("6B1T")
print("Nós:", G_6b1t.number_of_nodes())
print("Arestas:", G_6b1t.number_of_edges())
print("Comunidades:", len(communities_6b1t))
display(stats_6b1t)

# Cria uma tabela associando cada resíduo à comunidade detectada pelo Louvain.

df_communities_6b1t = pd.DataFrame([
    {
        "node": node,
        "chain": G_6b1t.nodes[node]["chain"],
        "resname": G_6b1t.nodes[node]["resname"],
        "resid": G_6b1t.nodes[node]["resid"],
        "community": partition_6b1t[node]
    }
    for node in G_6b1t.nodes()
])

df_communities_6b1t.to_csv(
    TABLES_DIR / "6B1T_communities.csv",
    index=False
)

df_communities_6b1t["community"].value_counts().sort_index()

# Gera o histograma e o gráfico log-log da distribuição de graus.
# Esta figura será usada na seção de análise topológica.

plot_degree_distribution(
    G_6b1t,
    "Distribuição de graus - 6B1T",
    FIGURES_DIR / "6B1T_degree_distribution.png"
)

# Salva a distribuição de graus em CSV para documentação dos resultados.

degrees_6b1t = [degree for _, degree in G_6b1t.degree()]

df_degree_distribution_6b1t = (
    pd.Series(degrees_6b1t)
    .value_counts()
    .sort_index()
    .reset_index()
)

df_degree_distribution_6b1t.columns = ["degree", "count"]
df_degree_distribution_6b1t["probability"] = (
    df_degree_distribution_6b1t["count"] / df_degree_distribution_6b1t["count"].sum()
)

df_degree_distribution_6b1t.to_csv(
    TABLES_DIR / "6B1T_degree_distribution.csv",
    index=False
)

df_degree_distribution_6b1t.head()

# Calcula centralidades viáveis para a rede 6B1T.
# Degree centrality e eigenvector centrality são calculadas de forma exata.
# Betweenness é calculada de forma aproximada, pois a versão exata é muito custosa.

start = time.time()

degree_c_6b1t = nx.degree_centrality(G_6b1t)

print("Degree centrality calculada.")
print("Tempo parcial:", time.time() - start)

# Calcula eigenvector centrality.
# Essa medida identifica nós conectados a outros nós também bem conectados.

start = time.time()

eigenvector_6b1t = nx.eigenvector_centrality(
    G_6b1t,
    max_iter=1000,
    tol=1e-06
)

print("Eigenvector centrality calculada.")
print("Tempo:", time.time() - start)

# Calcula betweenness centrality aproximada.
# A versão exata pode ser muito lenta para uma rede com mais de 12 mil nós.
# O parâmetro k define quantos nós serão usados como amostra.

start = time.time()

betweenness_6b1t_approx = nx.betweenness_centrality(
    G_6b1t,
    k=500,
    seed=42
)

print("Betweenness centrality aproximada calculada.")
print("Tempo:", time.time() - start)

# Opcional: tentativa de closeness centrality exata.
# Se demorar demais no Colab, interrompa a célula.
# Só mantenha no relatório se executar em tempo aceitável.

start = time.time()

closeness_6b1t = nx.closeness_centrality(G_6b1t)

print("Closeness centrality calculada.")
print("Tempo:", time.time() - start)

# Organiza as centralidades calculadas em uma tabela única.

df_centrality_6b1t = pd.DataFrame([
    {
        "node": node,
        "chain": G_6b1t.nodes[node]["chain"],
        "resname": G_6b1t.nodes[node]["resname"],
        "resid": G_6b1t.nodes[node]["resid"],
        "degree": G_6b1t.degree(node),
        "degree_centrality": degree_c_6b1t[node],
        "eigenvector_centrality": eigenvector_6b1t[node],
        "betweenness_centrality_approx": betweenness_6b1t_approx[node],
        "closeness_centrality": closeness_6b1t[node],
        "community": partition_6b1t[node]
    }
    for node in G_6b1t.nodes()
])

df_centrality_6b1t.to_csv(
    TABLES_DIR / "6B1T_centralities.csv",
    index=False
)

df_centrality_6b1t.sort_values("degree", ascending=False).head(20)

# Seleciona os resíduos mais centrais segundo diferentes medidas.

top_degree_6b1t = df_centrality_6b1t.sort_values(
    "degree",
    ascending=False
).head(20)

top_eigenvector_6b1t = df_centrality_6b1t.sort_values(
    "eigenvector_centrality",
    ascending=False
).head(20)

top_betweenness_6b1t = df_centrality_6b1t.sort_values(
    "betweenness_centrality_approx",
    ascending=False
).head(20)

top_degree_6b1t.to_csv(TABLES_DIR / "6B1T_top_degree.csv", index=False)
top_eigenvector_6b1t.to_csv(TABLES_DIR / "6B1T_top_eigenvector.csv", index=False)
top_betweenness_6b1t.to_csv(TABLES_DIR / "6B1T_top_betweenness_approx.csv", index=False)

display(top_degree_6b1t)
display(top_eigenvector_6b1t)
display(top_betweenness_6b1t)

# Visualiza a estrutura 6B1T em 3D, colorindo os resíduos
# de acordo com a comunidade detectada pelo Louvain.

import matplotlib.colors as mcolors

num_communities = df_communities_6b1t["community"].nunique()
cmap = plt.get_cmap("tab20")

community_colors = {}

for i in range(num_communities):
    rgb = cmap(i % 20)[:3]
    community_colors[i] = mcolors.to_hex(rgb)

view = py3Dmol.view(width=900, height=700)

with open(pdb_6b1t_1) as f:
    view.addModel(f.read(), "pdb")

with open(pdb_6b1t_2) as f:
    view.addModel(f.read(), "pdb")

view.setStyle({"cartoon": {"color": "lightgray"}})

for _, row in df_communities_6b1t.iterrows():
    color = community_colors[row["community"]]

    view.setStyle(
        {
            "chain": row["chain"],
            "resi": int(row["resid"])
        },
        {
            "cartoon": {"color": color}
        }
    )

show_3d_view(view, "Visualização 3D das comunidades da 6B1T")

# Visualiza em 3D os 20 resíduos com maior grau.
# A proteína fica em cinza e os resíduos mais conectados são destacados.

top_nodes = set(top_degree_6b1t["node"].tolist())

view = py3Dmol.view(width=900, height=700)

with open(pdb_6b1t_1) as f:
    view.addModel(f.read(), "pdb")

with open(pdb_6b1t_2) as f:
    view.addModel(f.read(), "pdb")

view.setStyle({"cartoon": {"color": "lightgray"}})

for node in top_nodes:
    data = G_6b1t.nodes[node]

    view.addStyle(
        {
            "chain": data["chain"],
            "resi": int(data["resid"])
        },
        {
            "stick": {
                "radius": 0.5,
                "color": "red"
            }
        }
    )

show_3d_view(view, "Visualização 3D dos resíduos mais conectados da 6B1T")

# Lista todos os arquivos gerados para conferir se as tabelas e figuras
# necessárias ao relatório foram salvas corretamente.

for root, dirs, files in os.walk(RESULTS_DIR):
    for file in files:
        print(os.path.join(root, file))

df_centrality_6b1t.describe()

top_degree_6b1t

display(top_eigenvector_6b1t)

display(top_betweenness_6b1t)

# Gráficos das principais centralidades
#
# Este bloco gera gráficos de barras contendo os 15 resíduos
# mais importantes segundo cada medida de centralidade.

def plot_top_centrality(df, column, title, filename, top_n=15):

    top = (
        df.sort_values(column, ascending=False)
          .head(top_n)
          .copy()
    )

    labels = (
        top["chain"] + ":" +
        top["resname"] + "-" +
        top["resid"].astype(str)
    )

    plt.figure(figsize=(10,5))

    plt.bar(labels, top[column])

    plt.xticks(rotation=70)
    plt.ylabel(column.replace("_"," ").title())
    plt.title(title)

    plt.tight_layout()

    plt.savefig(
        FIGURES_DIR / filename,
        dpi=300,
        bbox_inches="tight"
    )

    plt.show()


plot_top_centrality(
    df_centrality_6b1t,
    "degree_centrality",
    "Top 15 resíduos por Degree Centrality",
    "top_degree_centrality.png"
)

plot_top_centrality(
    df_centrality_6b1t,
    "eigenvector_centrality",
    "Top 15 resíduos por Eigenvector Centrality",
    "top_eigenvector_centrality.png"
)

plot_top_centrality(
    df_centrality_6b1t,
    "betweenness_centrality_approx",
    "Top 15 resíduos por Betweenness Centrality (aproximada)",
    "top_betweenness_centrality.png"
)

# Visualização 3D dos resíduos mais conectados
#
# Destaca na estrutura tridimensional os resíduos que
# apresentam maior Degree Centrality.

top_nodes = set(
    top_degree_6b1t["node"].tolist()
)

view = py3Dmol.view(width=900, height=700)

with open(pdb_6b1t_1) as f:
    view.addModel(f.read(), "pdb")

with open(pdb_6b1t_2) as f:
    view.addModel(f.read(), "pdb")

# proteína inteira em cinza
view.setStyle(
    {"cartoon": {"color": "lightgray"}}
)

# resíduos mais conectados em vermelho
for node in top_nodes:

    info = G_6b1t.nodes[node]

    view.addStyle(
        {
            "chain": info["chain"],
            "resi": int(info["resid"])
        },
        {
            "stick": {
                "radius": 0.45,
                "color": "red"
            }
        }
    )

show_3d_view(view, "Visualização 3D dos resíduos com maior Degree Centrality")









